# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - BriefBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: "https://briefbot.azurewebsites.net"

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt update -y
          sudo apt install -y ffmpeg
      
      - name: Setting environment variables
        run: |
          echo BOT_TOKEN=${{ env.BOT_TOKEN }} >> .env
          echo API_KEY=${{ env.API_KEY }} >> .env

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'BriefBot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9D8B3E9D6AF9430E824B0E69FF7339B8 }}
          package: .
